# HPA pour backend Node.js
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-node-hpa
  namespace: student-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-node
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# HPA pour backend .NET
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-dotnet-hpa
  namespace: student-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-dotnet
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# HPA pour backend Spring Boot
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-springboot-hpa
  namespace: student-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-springboot
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
